spring:
  # 配置数据库连接池
  datasource:
    url: jdbc:mysql://47.107.229.132:3306/we7?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: blxf
    password: 457862154
  ### 配置Redis
  redis:
    database: 0
    host: 10.0.0.32
    port: 6379
    password: 1470634109